In [83]:
import os
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [84]:
root_folder=r"C:\Users\irene\OneDrive\Desktop\python1"

In [85]:
df=pd.read_csv(r"C:\Users\irene\OneDrive\Desktop\python1\demand_forecasting.csv")
df.head()

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Price,Discount,Weather Condition,Promotion,Competitor Pricing,Seasonality,Epidemic,Demand
0,2022-01-01,S001,P0001,Electronics,North,195,102,252,72.72,5,Snowy,0,85.73,Winter,0,115
1,2022-01-01,S001,P0002,Clothing,North,117,117,249,80.16,15,Snowy,1,92.02,Winter,0,229
2,2022-01-01,S001,P0003,Clothing,North,247,114,612,62.94,10,Snowy,1,60.08,Winter,0,157
3,2022-01-01,S001,P0004,Electronics,North,139,45,102,87.63,10,Snowy,0,85.19,Winter,0,52
4,2022-01-01,S001,P0005,Groceries,North,152,65,271,54.41,0,Snowy,0,51.63,Winter,0,59

In [86]:
df['Date'] = pd.to_datetime(df['Date'])
df=df.sort_values('Date')
df=pd.get_dummies(df, columns=['Store ID', 'Product ID', 'Category', 'Region', 'Weather Condition', 'Seasonality'])
df=df.drop("Date", axis=1)
df.head()

,Inventory Level,Units Sold,Units Ordered,Price,Discount,Promotion,Competitor Pricing,Epidemic,Demand,Store ID_S001,...,Region_South,Region_West,Weather Condition_Cloudy,Weather Condition_Rainy,Weather Condition_Snowy,Weather Condition_Sunny,Seasonality_Autumn,Seasonality_Spring,Seasonality_Summer,Seasonality_Winter
0,195,102,252,72.72,5,0,85.73,0,115,True,...,False,False,False,False,True,False,False,False,False,True
72,136,104,385,20.24,10,0,18.90,0,110,False,...,False,True,False,False,True,False,False,False,False,True
71,111,111,113,118.15,0,0,133.46,0,103,False,...,False,True,False,False,True,False,False,False,False,True
70,195,60,293,52.89,0,0,62.29,0,61,False,...,False,True,False,False,True,False,False,False,False,True
69,223,120,597,30.02,0,0,29.15,0,128,False,...,False,True,False,False,True,False,False,False,False,True

In [87]:
df=df.drop("Epidemic", axis=1)
df.head()

,Inventory Level,Units Sold,Units Ordered,Price,Discount,Promotion,Competitor Pricing,Demand,Store ID_S001,Store ID_S002,...,Region_South,Region_West,Weather Condition_Cloudy,Weather Condition_Rainy,Weather Condition_Snowy,Weather Condition_Sunny,Seasonality_Autumn,Seasonality_Spring,Seasonality_Summer,Seasonality_Winter
0,195,102,252,72.72,5,0,85.73,115,True,False,...,False,False,False,False,True,False,False,False,False,True
72,136,104,385,20.24,10,0,18.90,110,False,False,...,False,True,False,False,True,False,False,False,False,True
71,111,111,113,118.15,0,0,133.46,103,False,False,...,False,True,False,False,True,False,False,False,False,True
70,195,60,293,52.89,0,0,62.29,61,False,False,...,False,True,False,False,True,False,False,False,False,True
69,223,120,597,30.02,0,0,29.15,128,False,False,...,False,True,False,False,True,False,False,False,False,True

In [88]:
#data prep
y= df['Demand']
y

0        115
72       110
71       103
70        61
69       128
        ...
75927     96
75926    109
75925    118
75935    105
75999     73
Name: Demand, Length: 76000, dtype: int64

In [89]:
x= df.drop('Demand', axis=1)
x

,Inventory Level,Units Sold,Units Ordered,Price,Discount,Promotion,Competitor Pricing,Store ID_S001,Store ID_S002,Store ID_S003,...,Region_South,Region_West,Weather Condition_Cloudy,Weather Condition_Rainy,Weather Condition_Snowy,Weather Condition_Sunny,Seasonality_Autumn,Seasonality_Spring,Seasonality_Summer,Seasonality_Winter
0,195,102,252,72.72,5,0,85.73,True,False,False,...,False,False,False,False,True,False,False,False,False,True
72,136,104,385,20.24,10,0,18.90,False,False,False,...,False,True,False,False,True,False,False,False,False,True
71,111,111,113,118.15,0,0,133.46,False,False,False,...,False,True,False,False,True,False,False,False,False,True
70,195,60,293,52.89,0,0,62.29,False,False,False,...,False,True,False,False,True,False,False,False,False,True
69,223,120,597,30.02,0,0,29.15,False,False,False,...,False,True,False,False,True,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75927,85,81,94,26.98,0,0,24.65,False,True,False,...,True,False,False,False,True,False,False,False,False,True
75926,414,126,0,26.84,10,0,29.55,False,True,False,...,True,False,False,False,True,False,False,False,False,True
75925,98,96,117,63.58,10,0,76.22,False,True,False,...,True,False,False,False,True,False,False,False,False,True
75935,88,78,0,91.50,5,0,85.74,False,True,False,...,True,False,False,False,True,False,False,False,False,True
75999,126,63,59,25.78,10,0,29.32,False,False,False,...,False,False,False,False,True,False,False,False,False,True

In [90]:
#data split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [91]:
x_train

,Inventory Level,Units Sold,Units Ordered,Price,Discount,Promotion,Competitor Pricing,Store ID_S001,Store ID_S002,Store ID_S003,...,Region_South,Region_West,Weather Condition_Cloudy,Weather Condition_Rainy,Weather Condition_Snowy,Weather Condition_Sunny,Seasonality_Autumn,Seasonality_Spring,Seasonality_Summer,Seasonality_Winter
42925,172,53,0,44.80,20,1,54.04,False,True,False,...,True,False,False,True,False,False,False,True,False,False
67321,178,77,0,33.06,0,0,29.35,False,True,False,...,True,False,False,False,True,False,True,False,False,False
41751,164,39,0,80.61,10,0,70.66,False,False,True,...,False,False,False,False,False,True,False,False,False,True
10787,155,148,191,72.04,10,0,66.58,False,False,False,...,False,False,True,False,False,False,False,True,False,False
56486,240,125,212,81.65,5,0,88.23,False,False,False,...,False,False,False,True,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37130,179,71,0,83.00,10,0,79.90,False,True,False,...,True,False,False,False,False,True,False,False,False,True
6207,103,103,104,47.63,0,0,54.01,True,False,False,...,False,False,True,False,False,False,False,True,False,False
54838,197,141,0,73.86,25,1,82.45,False,True,False,...,True,False,False,False,False,True,False,False,True,False
812,100,100,98,30.92,10,0,36.09,True,False,False,...,False,False,False,False,False,True,False,False,False,True
15729,112,112,104,91.98,10,0,86.20,False,True,False,...,True,False,False,True,False,False,False,False,True,False

In [92]:
x_test

,Inventory Level,Units Sold,Units Ordered,Price,Discount,Promotion,Competitor Pricing,Store ID_S001,Store ID_S002,Store ID_S003,...,Region_South,Region_West,Weather Condition_Cloudy,Weather Condition_Rainy,Weather Condition_Snowy,Weather Condition_Sunny,Seasonality_Autumn,Seasonality_Spring,Seasonality_Summer,Seasonality_Winter
53793,215,114,0,156.65,15,1,171.98,False,False,False,...,False,False,True,False,False,False,False,False,True,False
61160,919,136,0,11.80,10,0,10.26,False,False,False,...,False,True,False,False,False,True,True,False,False,False
72023,422,213,555,42.08,25,1,37.53,False,True,False,...,True,False,True,False,False,False,False,False,False,True
56995,198,69,0,31.46,10,0,34.87,False,False,False,...,False,False,False,True,False,False,False,False,True,False
20946,165,156,0,17.49,5,0,19.08,False,False,True,...,False,False,False,True,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44571,151,46,0,99.64,10,0,91.86,False,False,False,...,False,True,True,False,False,False,False,True,False,False
21106,1383,234,0,31.57,5,0,35.19,True,False,False,...,False,False,False,False,False,True,False,False,True,False
11359,560,117,0,72.74,10,0,79.95,False,False,True,...,False,False,False,False,False,True,False,True,False,False
48624,429,50,0,80.27,5,0,78.89,False,True,False,...,True,False,False,False,False,True,False,True,False,False
57485,1127,165,0,65.50,10,0,75.34,False,False,False,...,False,False,True,False,False,False,False,False,True,False

In [102]:
#model building
#linear regression
from sklearn.linear_model import LinearRegression
lr= LinearRegression()
lr.fit(x_train, y_train)
y_predr= lr.predict(x_train)
y_prede= lr.predict(x_test)
print("Predictions:", y_predr)

Predictions: [ 75.32559757  84.92427692  43.97422763 ... 156.02276212 112.49745621
 134.02914816]

In [103]:
print("Predictions:", y_prede)

Predictions: [117.0096399  128.34014178 224.30558246 ... 119.35404209  65.50498128
 156.33016784]

In [98]:
from sklearn.metrics import mean_absolute_error
preds=lr.predict(x_test)
mae= mean_absolute_error(y_test, preds)
print("Mean Absolute Error:", mae)

Mean Absolute Error: 17.221717616562735

In [104]:
#random forest
from sklearn.ensemble import RandomForestRegressor
rf= RandomForestRegressor(n_estimators=100, random_state=42)
rf.fit(x_train, y_train)
y_predrf= rf.predict(x_test)
print("Predictions:", y_predrf)

Predictions: [116.64 144.46 200.43 ... 125.32  58.36 163.11]